plex:
  host: https://my.plex.server
  token: xxxxxxxxxxxxxxxxx
api:
  listen_addr: ":8080"
ffmpeg:
  # libx264 is the default (software) encoder.
  # h264_vaapi is also supported for faster hardware encoding with Intel quicksync (untested)
  # and AMD GPUs (tested on Linux).
  # Set to h264_nvenc for Nvidia GPUs.
  codec: libx264
